name: CMake

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}
        run: ls -Rl

      - name: Checkout FreeType
        shell: bash
        working-directory: ${{runner.workspace}}/external
        run: curl https://download.savannah.gnu.org/releases/freetype/freetype-2.10.0.tar.bz2

      - name: Show Result
        shell: bash
        working-directory: ${{runner.workspace}}/external
        run: ls -Rl

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
