on: [push]

jobs:
  contexts:
    runs-on: windows-latest
    # env:
    #   context-github: ${{toJson(github)}}
    #   context-env: ${{toJson(env)}}
    #   job
    #   steps
    #   runner
    #   secrets
    #   strategy
    #   matrix
    #   needs
    steps:
    - name: context/github
      shell: bash
      env:
        jsonstr: ${{toJson(github)}}
      run: echo "$jsonstr"

  windows-latest:
    runs-on: windows-latest
    steps:
    - name: printenv
      shell: cmd
      run: set
