on: [push]

env:
  BUILD_TYPE: Release
  Platform: Win32

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/setup-msbuild@v1.0.2

      - name: setup directories
        run: |
             mkdir nuget

      - working-directory: nuget
        run: nuget install -ExcludeVersion VideoLAN.LibVLC.Windows

      - run: vcpkg install curl:x86-windows-static-md
      - run: vcpkg install freeimage:x86-windows-static-md
      - run: vcpkg install freetype:x86-windows-static-md
      - run: vcpkg install rapidjson:x86-windows-static-md
      - run: vcpkg install sdl2:x86-windows-static-md

      - run: cmake -E make_directory ${{runner.workspace}}/build

      - run: tree /f /a
      - run: tree /f /a c:/vcpkg/installed
